import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navbar.js"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Preston's Website",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '/images/big-logo.png',
      media: '/images/big-logo.png'
      }
    ]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
